title: The Wanna be Clojure Girl ..
description: 
highlighter: rouge
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions

markdown: kramdown

kramdown:
 input: GFM
 hard_wrap: false
 syntax_highlighter_opts:
   disable: true
